# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Gordon Tang
tagline:          'Data, UX industrial engineer.'
description:      'Data, UX industrial engineer.'
url:              https://gordontang.github.io/
baseurl:          /

author:
  name:           'Gordon Tang'
  url:            https://twitter.com/tangghy

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/gordontang/gordontang.github.io
